version: 2

anchors:
    - &image_default circleci/node:10.1.0
    - &working_directory ~/gdrive-lib
jobs:
  build:
    docker:
    - image: *image_default
    working_directory: *working_directory
    steps:
    - checkout
    - restore_cache:
        key: gdrive-lib-dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Running Build setup
        command: npm run build
    - save_cache:
        key: gdrive-lib-dependency-cache-{{ checksum "package.json" }}
        paths:
        - node_modules
    - persist_to_workspace:
        root: .
        paths:
        - .
  test-vuln:
    docker:
    - image: *image_default
    working_directory: *working_directory
    steps:
    - attach_workspace:
        at: .-
    - run:
        name: Running Vuln Tests
        command: npm run test:vuln
  test-mocha:
    docker:
    - image: *image_default
    working_directory: *working_directory
    steps:
    - attach_workspace:
        at: .-
    - run:
        name: Running mocha tests
        command: npm run test:mocha
  test-eslint:
    docker:
    - image: *image_default
    working_directory: *working_directory
    steps:
    - attach_workspace:
        at: .-
    - run:
        name: Running linter
        command: npm run test:lint

workflows:
  version: 2
  gdrive-lib-all:
    jobs:
    - build
    - test-vuln:
        requires:
        - build
    - test-mocha:
        requires:
        - build
    - test-eslint:
        requires:
        - build
