version: 2

anchors:
    - &image_default circleci/node:10.1.0
    - &working_directory ~/gdrive-lib
jobs:
  test-vuln:
    docker:
    - image: *image_default
    working_directory: *working_directory
    steps:
    - attach_workspace:
        at: *working_directory
    - run:
        name: Running Vuln Tests
        command: yarn run test:vuln
  test-mocha:
    docker:
    - image: *image_default
    working_directory: *working_directory
    steps:
    - attach_workspace:
        at: *working_directory
    - run:
        name: Running mocha tests
        command: yarn run test:mocha
  test-eslint:
    docker:
    - image: *image_default
    working_directory: *working_directory
    steps:
    - attach_workspace:
        at: *working_directory
    - run:
        name: Running linter
        command: yarn run test:lint

workflows:
  version: 2
  gdrive-lib-all:
    jobs:
    - test-vuln
    - test-mocha
    - test-eslint
